---
# Test framework: "xcuitest" or "espresso"
testFramework: xcuitest
 
# Path to the app's .ipa or .app.
app: ./SimpleLocationApp.ipa
# app: 84
 
# Path to the test runner app's .ipa or .app.
test: ./SimpleLocationAppUITests-Runner.ipa
# test: 83
 
# Path where XML test reports will be saved.
xmlFolder: ./results/
 
# Define a list of devices on which the tests should be executed.
devices:

- datacenter: US
  platformVersion: 13

- datacenter: US
  platformVersion: 14

- datacenter: EU
  platformVersion: 13

- datacenter: EU
  platformVersion: 14